version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: crr
      POSTGRES_PASSWORD: crrpass
      POSTGRES_DB: crr
  kafka:
    image: bitnami/kafka:latest
  zookeeper:
    image: bitnami/zookeeper:latest
  redis:
    image: redis:7
  backend:
    build: ../backend
    depends_on: [postgres,kafka,redis]
    ports: ["8000:8000"]
  grafana:
    image: grafana/grafana:latest
    ports: ["3001:3000"]
