apiVersion: apps/v1
kind: Deployment
metadata:
  name: crr-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crr-backend
  template:
    metadata:
      labels:
        app: crr-backend
    spec:
      containers:
        - name: backend
          image: calculated-risk-returns-backend:latest
          ports:
            - containerPort: 8000
